version: '3'
services:

  #PHP Service
  php:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php
    working_dir: /var/app
    depends_on:
        - mysql
          
  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /var/app
    # user: "${UID}:${GID}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/:/var/app/
      - ./etc/nginx/logs:/var/log/nginx/
    depends_on:
      - php
      - mysql
  #MySQL Service
  mysql:
    image: mysql
    container_name: mysql
    env_file:
     - .env
    working_dir: /var/app
    ports:
      - "3306:3306"

    volumes:
      -  ./mysql/data:/var/lib/mysql
        
  #Make migrations
  migrations:   
    env_file:
        - .env
    build: 
        context: .
        dockerfile: Dockerfile.migrate
        args:
         - DATABASE_DSN=${DATABASE_DSN}
         - DATABASE_USERNAME=${MYSQL_USER}
         - DATABASE_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
        - mysql
