version: '3'
services:

  #PHP Service
  php:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
      args:
         - DATABASE_USERNAME=${DATABASE_USERNAME}
         - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    container_name: php
    working_dir: /var/app
    depends_on:
        - mysql
          
  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/app
      - /var/log/docker-nginx:/var/log/nginx/
    depends_on:
      - php
      - mysql
        
  #MySQL Service
  mysql:
    image: mysql
    container_name: mysql
    env_file:
     - .env
    working_dir: /var/app
    ports:
      - "3306:3306"

    volumes:
      -  ./mysql/data:/var/lib/mysql
        
  #Make migrations
  migrations:   
    build: 
        context: .
        dockerfile: Dockerfile.migrate
    depends_on:
        - mysql
