version: '3'
services:

  #PHP Service
  php:
    build:
      context: ./php/
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_DSN=${DATABASE_DSN}
    working_dir: /var/app
    depends_on:
      - db

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/app
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php
      - mysqldb
  #MySQL Service
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3306:3306"

    volumes:
      - dbdata:/var/lib/mysql


