version: '3'
services:

  #PHP Service
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php
    #restart: always
    env_file:
      - .env
    environment:
            - DATABASE_USERNAME:root
            - DATABASE_PASSWORD:rootroot
            - DATABASE_DSN:mysql:host=localhost;port=3306;dbname=testdb
    working_dir: /var/app
    depends_on:
      - mysql

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    #restart: always
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./index.php:/var/app/index.php
      - /var/log/docker-nginx:/var/log/nginx/
    depends_on:
      - php
      - mysql
  #MySQL Service
  mysql:
    image: mysql
    container_name: mysql
    # restart: always
    #env_file:
    # - .env
    #environment:
    #    - DATABASE_USERNAME:root
    #    - DATABASE_PASSWORD:rootroot
    #    - DATABASE_DSN:mysql:host=localhost;port=3306;dbname=testdb
    working_dir: /var/app


    ports:
      - "3306:3306"

    volumes:
      -  ./mysql/data:/var/lib/mysql

