version: '3'
services:

  #PHP Service
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php
    #restart: always
    env_file:
      - .env
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DSN=${DATABASE_DSN}
    working_dir: /var/app
    depends_on:
      - mysql

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    #restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/app
      - /var/log/docker-nginx:/var/log/nginx
    depends_on:
      - php
      - mysql
  #MySQL Service
  mysql:
    image: mysql
    container_name: mysql
    # restart: always
    env_file:
      - .env
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}


    ports:
      - "3306:3306"

    volumes:
      -  ./mysql/data:/var/lib/mysql

